name: Share to Slack

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-pull-request:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - id: reviews
        uses: github-actions-tools/gh-reviews-count@v0.0.1
        with:
          pull_number: ${{ github.event.pull_request.number }}

      - name: Echo
        if: steps.reviews.outputs.approved >= 2
        run: echo "${{steps.reviews.outputs.approved}}"
